### ISSUE TITLE
Not working with Dropwizard 1.2+

### ISSUE THREAD

**Issue by psimonazzi** [yunspace/dropwizard-xml#8]
Not working with new Dropwizard 1.2, probably because of the Logback changes?
App fails at runtime with:
```
Exception in thread "main" java.lang.NoClassDefFoundError: io/dropwizard/jackson/LogbackModule
at com.yunspace.dropwizard.xml.XmlBundle.<init>(XmlBundle.java:17)
```
