### PR TITLE
Removed Logback dependency to be compatible with Dropwizard 1.2.x

### LINKED ISSUE #8: Not working with Dropwizard 1.2+
Not working with new Dropwizard 1.2, probably because of the Logback changes?
App fails at runtime with:
```
Exception in thread "main" java.lang.NoClassDefFoundError: io/dropwizard/jackson/LogbackModule
at com.yunspace.dropwizard.xml.XmlBundle.<init>(XmlBundle.java:17)
```

### PR DESCRIPTION
**Pull request by psimonazzi**
Fixes #8

### CODE REVIEW

**Comment by aioobe** [comment]
Any idea if/when this will get merged? I'm blocked by this too.

**Comment by mrserverless** [comment]
Sorry @psimonazzi @aioobe, totally missed this. Thanks for the contribution.
